### ISSUE TITLE
unable to open device

### ISSUE THREAD

**Issue by DAigory** [ederfmartins/rgb_keyboard#4] opened 2021-12-11 03:59 UTC
ubuntu 20

hi. after error I tried to open device by terminal. I can open device with  0x6005 and it works and changing light, but it is no keyboard and I need 0xce00 but it getting error (unable to open device)

hidraw = hid.Device(0x048d, 0xce00)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/hid-1.0.4-py3.8.egg/hid/__init__.py", line 130, in __init__
    raise HIDException('unable to open device')
hid.HIDException: unable to open device

device lis:
sudo hwinfo --keyboard
25: USB 00.0: 10800 Keyboard                                    
  [Created at usb.122]
  Unique ID: fHJ1.DH42a1CsGp1
  Parent ID: k4bc.2DFUsyrieMD
  SysFS ID: /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.0
  SysFS BusID: 1-10:1.0
  Hardware Class: keyboard
  Model: "Integrated Technology Express ITE Device(8291)"
  Hotplug: USB
  Vendor: usb 0x048d "Integrated Technology Express, Inc."
  Device: usb 0x6005 "ITE Device(8291)"
  Revision: "0.03"
  Speed: 12 Mbps
  Module Alias: "usb:v048Dp6005d0003dc00dsc00dp00ic03isc01ip01in00"
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #35 (Hub)

27: USB 00.0: 10800 Keyboard
  [Created at usb.122]
  Unique ID: MtLc.6ZSjsesf2m6
  Parent ID: k4bc.2DFUsyrieMD
  SysFS ID: /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0
  SysFS BusID: 1-6:1.0
  Hardware Class: keyboard
  Model: "Integrated Technology Express ITE Device(8291)"
  Hotplug: USB
  Vendor: usb 0x048d "Integrated Technology Express, Inc."
  Device: usb 0xce00 "ITE Device(8291)"
  Revision: "0.02"
  Speed: 12 Mbps
  Module Alias: "usb:v048DpCE00d0002dc00dsc00dp00ic03isc01ip01in00"
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #35 (Hub)

43: PS/2 00.0: 10800 Keyboard
  [Created at input.226]
  Unique ID: c3zD.+49ps10DtUF
  Hardware Class: keyboard
  Model: "AT Translated Set 2 keyboard"
  Vendor: 0x0001 
  Device: 0x0001 "AT Translated Set 2 keyboard"
  Compatible to: int 0x0211 0x0001
  Device File: /dev/input/event4
  Device Files: /dev/input/event4, /dev/input/by-path/platform-i8042-serio-0-event-kbd
  Device Number: char 13:68
  Driver Info #0:
    XkbRules: xfree86
    XkbModel: pc104
  Config Status: cfg=new, avail=yes, need=no, active=unknown

**Comment by ederfmartins** [comment] 2021-12-16 22:33
Hi @DAigory,
Let's try to fix this error :)
Looking at hid/init.py it seen that you have some permission issue. If you're running with root privileges, in theory you should be able to connect to the keyboard.
from hid/init.py

```
def __init__(self, vid=None, pid=None, serial=None, path=None):
        if path:
            self.__dev = hidapi.hid_open_path(path)
        elif serial:
            serial = ctypes.create_unicode_buffer(serial)
            self.__dev = hidapi.hid_open(vid, pid, serial)
        elif vid and pid:
            self.__dev = hidapi.hid_open(vid, pid, None)
        else:
            raise ValueError('specify vid/pid or path')

        if not self.__dev:
            raise HIDException('unable to open device')
```
The exception occurred cause hidapi fail to open the device. Which generally indicates a permission problem. I'm not able to reproduce this error in my machine. The problem seen to be related to your Ubuntu installation. As a workaround, you could add a udev rule to give permission to your user (https://askubuntu.com/questions/15570/configure-udev-to-change-permissions-on-usb-hid-device) and try again (`sudo python -c "import hid; hid.Device(0x048d, 0xce00)"`).

**Comment by DAigory** [comment] 2021-12-17 02:18
hi. I added to 
```
/etc/udev/rules.d   50-usb-scale.conf  
SUBSYSTEM=="usb", ATTRS{idVendor}=="0x048d", ATTR{idProduct}=="0xce00", MODE="0666"
```
restart 
everything works fine now! thanks).

**Comment by ederfmartins** [comment] 2021-12-17 20:12
It is very nice to hear that, I will close this issue and update the readme

**Closed as completed** 2021-12-17 20:31 UTC
Labels: documentation
